//
//  ConversationTextFilterTests.swift
//
//  Tests for the slash-command / meta-text filter used to derive session
//  titles and last-message previews. Regression coverage for the bug
//  where /init sessions showed "<command-message>init</command-message>…"
//  as the title instead of the expanded prompt.
//

import Foundation

@main
struct ConversationTextFilterTests {
    static func main() {
        // MARK: - isSlashCommandOrMetaText

        test("isSlashCommandOrMetaText catches <command-message>") {
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText("<command-message>init</command-message>"),
                "<command-message> prefix should be filtered"
            )
        }

        test("isSlashCommandOrMetaText catches <command-name>") {
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText("<command-name>/init</command-name>"),
                "<command-name> prefix should be filtered"
            )
        }

        test("isSlashCommandOrMetaText catches the real /init payload") {
            // This is literally what Claude Code writes to JSONL for a /init invocation.
            let raw = "<command-message>init</command-message>\n<command-name>/init</command-name>"
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText(raw),
                "real /init payload should be filtered (regression)"
            )
        }

        test("isSlashCommandOrMetaText catches leading whitespace + command tag") {
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText("  \n<command-message>foo</command-message>"),
                "leading whitespace shouldn't defeat the filter"
            )
        }

        test("isSlashCommandOrMetaText catches <local-command-stdout>") {
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText("<local-command-stdout>\nResult\n</local-command-stdout>"),
                "<local-command-*> should be filtered"
            )
        }

        test("isSlashCommandOrMetaText catches Caveat: prefix") {
            assertTrue(
                ConversationTextFilter.isSlashCommandOrMetaText("Caveat: The messages below were generated by the user"),
                "Caveat: prefix should be filtered"
            )
        }

        test("isSlashCommandOrMetaText does NOT filter real user text") {
            assertTrue(
                !ConversationTextFilter.isSlashCommandOrMetaText("Please analyze this codebase"),
                "normal user text should pass through"
            )
            assertTrue(
                !ConversationTextFilter.isSlashCommandOrMetaText("fix: the overlay is broken"),
                "text starting with lowercase should pass"
            )
        }

        test("isSlashCommandOrMetaText doesn't over-match on text containing < char") {
            assertTrue(
                !ConversationTextFilter.isSlashCommandOrMetaText("if x < 10 then ..."),
                "code-like text with < should pass"
            )
            assertTrue(
                !ConversationTextFilter.isSlashCommandOrMetaText("<div>hello</div>"),
                "HTML-ish text should pass (doesn't start with <command)"
            )
        }

        // MARK: - extractUserText (string content form)

        test("extractUserText returns plain string content unchanged") {
            let msg: [String: Any] = ["content": "Hello world"]
            assertEqual(ConversationTextFilter.extractUserText(from: msg), "Hello world", "plain string passthrough")
        }

        test("extractUserText returns nil for a command-only string") {
            let msg: [String: Any] = [
                "content": "<command-message>init</command-message>\n<command-name>/init</command-name>"
            ]
            assertTrue(
                ConversationTextFilter.extractUserText(from: msg) == nil,
                "command-only content should yield nil"
            )
        }

        // MARK: - extractUserText (array content form)

        test("extractUserText pulls the first text block from an array content") {
            let msg: [String: Any] = [
                "content": [
                    ["type": "text", "text": "Please analyze this codebase and create a CLAUDE.md file"]
                ]
            ]
            assertEqual(
                ConversationTextFilter.extractUserText(from: msg),
                "Please analyze this codebase and create a CLAUDE.md file",
                "first text block"
            )
        }

        test("extractUserText skips command-only text blocks and returns the next real one") {
            let msg: [String: Any] = [
                "content": [
                    ["type": "text", "text": "<command-message>init</command-message>"],
                    ["type": "text", "text": "Please analyze this codebase"]
                ]
            ]
            assertEqual(
                ConversationTextFilter.extractUserText(from: msg),
                "Please analyze this codebase",
                "second block wins"
            )
        }

        test("extractUserText ignores non-text blocks in array content") {
            let msg: [String: Any] = [
                "content": [
                    ["type": "tool_use", "name": "Read", "input": ["file_path": "/tmp/x"]],
                    ["type": "text", "text": "Here is the user's real message"]
                ]
            ]
            assertEqual(
                ConversationTextFilter.extractUserText(from: msg),
                "Here is the user's real message",
                "non-text blocks are skipped"
            )
        }

        test("extractUserText returns nil when array has only filtered/non-text blocks") {
            let msg: [String: Any] = [
                "content": [
                    ["type": "tool_use", "name": "Read"],
                    ["type": "text", "text": "<command-args>--force</command-args>"]
                ]
            ]
            assertTrue(
                ConversationTextFilter.extractUserText(from: msg) == nil,
                "all-meta array yields nil"
            )
        }

        test("extractUserText returns nil when content is missing or wrong type") {
            assertTrue(
                ConversationTextFilter.extractUserText(from: [:]) == nil,
                "empty dict yields nil"
            )
            assertTrue(
                ConversationTextFilter.extractUserText(from: ["content": 42]) == nil,
                "numeric content yields nil"
            )
        }

        finish("ConversationTextFilterTests")
    }
}
